<?php

namespace ApiBundle\Repository;
use ApiBundle\Entity\Competition;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
	
	
	public function findTeamByCompetitionPlayers(Competition $competition)
    {
	    $query = $this->_em->createQuery("SELECT distinct t.id,
	    										t.city,
	    										t.country,
	    										t.coach,
	    										t.president 
										  FROM ApiBundle:Team t 
										  LEFT JOIN ApiBundle:Player p WITH p.team = t.id 
										  LEFT JOIN ApiBundle:PlayerCompetition pc WITH pc.player = p.id
										  WHERE 
										  		pc.competition = ".$competition->getId());
		$teams = $query->getResult();
	    return $teams;
  
    }
}
